### ISSUE TITLE
What's the best way to override properties at runtime?

### ISSUE THREAD

**Issue by who** [arteam/jdit#3]
I use docker-maven-plugin in my pre-integration-test phase to create an in-memory mysql database that's populated with a schema by Flyway. The port for the mysql database is random, and is set into an environment variable. 

My question: 

How do I override the jdit.properties file with the value from an environment variable?

**Comment by arteam** [comment]
Hi, you could try use Maven filtering for resources. Something like that:
```xml
<testResources>
  <testResource>
     <directory>src/test/resource</directory>
     <filtering>true</filtering>
  <testResource>
</testResources>
```

Then, in your `jdit.properties` you could refer to an environment variable like as `${env.DOCKER_PORT}`. Maven should be able to replace the expression to the value f the variable.

**Comment by arteam** [comment]
Alternatively, you could write to write a custom DBIFactory which populates the current `Properties` from the environment variables and then delegates a call to DropwizardDBIFactory. You can set the factory class in the `dbi.factory` property.

**Comment by who** [comment]
@arteam 

The latter of the two approaches works best for my case, as the environment variable isn't populated until the `integration-test` maven phase, which comes after the maven test resource preparation.  

I was able to get it working with this: 

**jdit.properties**
```
db.url=jdbc:mysql://localhost:${PORT}/test?serverTimezone=UTC
db.username=user
db.password=password
schema.migration.enabled=false
dbi.factory=com.github.who.myapp.integration.CustomDBIFactory
```

**CustomDBIFactory**

```
package com.github.who.myapp.integration;
import com.github.arteam.jdit.DBIFactory;
import org.skife.jdbi.v2.DBI;
import org.skife.jdbi.v2.logging.PrintStreamLog;
import java.util.Properties;

public class CustomDBIFactory implements DBIFactory {
    @Override
    public DBI createDBI(Properties properties) {
        String port = System.getenv("DYNAMIC_DOCKER_MYSQL_PORT");
        String jdbcURL = properties.getProperty("db.url").replace("${PORT}", port);

        DBI dbi = new DBI(jdbcURL, properties.getProperty("db.username"),
                properties.getProperty("db.password"));
        dbi.setSQLLog(new PrintStreamLog());
        return dbi;
    }
}
```
