### ISSUE TITLE
Is there a way to optionally skip sweepData?

### ISSUE THREAD

**Issue by who** [arteam/jdit#4]
It would be helpful to have the option to skip the `databaseMaintenance.sweepData()` call. I can't think of a good way to do this unless I extend `DBIRunner` and implement my own `methodBlock` function.

**Comment by arteam** [comment]
Sorry it took long to response. 

> I can't think of a good way to do this unless I extend DBIRunner and implement my own methodBlock function.

I think it's the only possible way to do that right now. I will think about how it's possible to configure such behaviour from a configuration property, but right I can't see a simple approach.
